### ISSUE TITLE
Memo file table.fpt is missing or is invalid

### ISSUE THREAD

**Issue by theparker** [tombrothers/VfpClient#3]
Trying to create a dbf from DataTable but keep getting memo file is missing or invalid

`DataTable dTable = GetDataTableWithContents(); //returns a DataTable`

`var dbcCreator = new VfpClient.Utils.DbcCreator.DataTableDbcCreator(pathToNewDBF); //creates 3 files .dbf, .dct and .dcx`

`dbcCreator.Add(dTable); //error occurs here`

PS: Thanks for your effort in creating this project

**Comment by theparker** [comment]
[VFPClientLibraryTest.zip](https://github.com/tombrothers/VfpClient/files/1375203/VFPClientLibraryTest.zip)

Please find attached

**Comment by tombrothers** [comment]
The problem is that you are passing a dbf path to the DataTableDbcCreator constructor.  The path should be a dbc instead.  The Add method is what creates the dbf file.

**Comment by theparker** [comment]
thanks @tombrothers that fixed it.
