### ISSUE TITLE
Creating Tables in various DBF file versions

### ISSUE THREAD

**Issue by theparker** [tombrothers/VfpClient#4]
Hi @tombrothers 

Is it possible to create different versions of DBF using VfpClient?

[http://www.dbf2002.com/dbf-file-format.html](http://www.dbf2002.com/dbf-file-format.html)

I am trying to create DBF files to be used by an old VFP application however, exporting DataTable to DBF translates string as varchar. This makes the first byte in the file created as 0x32 (refer to the link above). What I need is a resulting DBF with first offset as 0x30. Is it possible to override the translation and translate strings as character? Thanks

**Comment by tombrothers** [comment]
There isn’t a way to configure this with the current build.  But it would be a simple change if you want to create your own build.  You just need to add a second parameter of true to the GetVfpStringType call in DataTableToTableConverter.cs -  line 96.

![image](https://user-images.githubusercontent.com/7569059/34298794-7f459452-e6ed-11e7-9f0e-f9d8c288d991.png)

**Comment by theparker** [comment]
Thanks for the swift response @tombrothers 
Will try this in the new year. For now, I simply run ALTER table on the DBF to convert varchar to character data types and it works.

Thanks for the effort you put into building and maintaining this great library.
