### ISSUE TITLE
Reading DateTime?  and Writing a Null Date

### ISSUE THREAD

**Issue by mPisano** [tombrothers/VfpClient#5]
See your updating the code :) 
I added this awhile ago to my source to support DateTime? in model
Figured since its "Beta" I might be able to add my hacks ;)

VfpClient (to check if DateTime and  value is 1899)
```
        static DateTime NullFoxDate = new DateTime(1899, 12, 30, 00, 00, 00);
        public override bool IsDBNull(int ordinal) {
            return Execute(() =>
            {
                var value = _dbDataReader.IsDBNull(ordinal);
                    var objvalue = _dbDataReader.GetValue(ordinal);
                    if (objvalue is DateTime)
                        if ((DateTime)objvalue == NullFoxDate)
                            value = true;
                return value;
            });
        }
```

EF2 Provider (use "", not NULL)
```
        public override VfpExpression Visit(VfpNullExpression expression) {
//            Write("CAST(NULL AS "); MPP Fix Date Cast
            Write("CAST(\"\" AS ");
            Write(GetSqlPrimitiveType(expression.ResultType));
            Write(")");

            return expression;
        }

```
Keep in mind if you use DateTime?  with your current code and try to write a null back you get a Syntax Error on the update.
Not sure if NULL is dependent on Engine Level... All fields are persisted up to the Datetime and the rest of the changes are blindly lost.

HTH
Mike Pisano

**Comment by tombrothers** [comment]
Can you create a pull request for these changes?

**Comment by mPisano** [comment]
Created 2 one for each

**Comment by tombrothers** [comment]
The changes are in the latest releases.
